source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!
project '/Users/Ricardo/Documents/Xcode Codes/Examen-CM/Examen-CM.xcodeproj'

target 'Examen-CM' do
pod 'GoogleMaps'
pod 'PayPal-iOS-SDK'
end
